import { StyleSheet } from "@react-pdf/renderer";

export const aiPdfStyles = StyleSheet.create({
  coverPage: {
    paddingTop: 64,
    paddingBottom: 64,
    paddingHorizontal: 40,
    fontSize: 11,
    fontFamily: "Helvetica",
    color: "#0b1220",
    backgroundColor: "#ffffff",
    justifyContent: "center",
  },
  coverCenter: {
    alignItems: "center",
    justifyContent: "center",
  },
  coverLogo: {
    width: 92,
    height: 92,
    borderRadius: 18,
    marginBottom: 18,
  },
  coverInstitute: {
    fontSize: 16,
    fontWeight: 700,
    marginBottom: 6,
  },
  coverDocType: {
    fontSize: 22,
    fontWeight: 700,
    marginBottom: 8,
  },
  coverMeta: {
    fontSize: 10,
    color: "#475569",
  },
  coverDivider: {
    marginTop: 22,
    marginBottom: 18,
    height: 1,
    width: "60%",
    backgroundColor: "#e5e7eb",
  },
  page: {
    paddingTop: 40,
    paddingBottom: 48,
    paddingHorizontal: 40,
    fontSize: 11,
    fontFamily: "Helvetica",
    color: "#0b1220",
    backgroundColor: "#ffffff",
  },
  header: {
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
    borderBottomStyle: "solid",
    paddingBottom: 16,
    marginBottom: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  brandLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  logo: {
    width: 34,
    height: 34,
    borderRadius: 8,
  },
  brandText: {
    flexDirection: "column",
  },
  brandName: {
    fontSize: 12,
    fontWeight: 700,
  },
  brandTagline: {
    fontSize: 9,
    color: "#64748b",
    marginTop: 2,
  },
  headerRight: {
    flexDirection: "column",
    alignItems: "flex-end",
  },
  docTitle: {
    fontSize: 16,
    fontWeight: 700,
  },
  docSubtitle: {
    fontSize: 9,
    color: "#64748b",
    marginTop: 3,
  },
  meta: {
    marginTop: 6,
    fontSize: 9,
    color: "#64748b",
  },
  section: {
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: 700,
    marginBottom: 6,
  },
  bodyText: {
    fontSize: 11,
    lineHeight: 1.45,
  },
  paragraph: {
    fontSize: 11,
    lineHeight: 1.55,
    marginBottom: 6,
  },
  mdH1: {
    fontSize: 16,
    fontWeight: 700,
    marginBottom: 10,
  },
  mdH2: {
    fontSize: 13,
    fontWeight: 700,
    marginBottom: 8,
    marginTop: 6,
  },
  mdH3: {
    fontSize: 12,
    fontWeight: 700,
    marginBottom: 6,
    marginTop: 4,
  },
  list: {
    marginBottom: 8,
  },
  listItem: {
    flexDirection: "row",
    gap: 6,
    marginBottom: 3,
  },
  listBullet: {
    width: 10,
    fontSize: 11,
    color: "#334155",
  },
  listContent: {
    flex: 1,
    fontSize: 11,
    lineHeight: 1.55,
  },
  codeBlock: {
    fontSize: 10,
    fontFamily: "Courier",
    backgroundColor: "#f1f5f9",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderStyle: "solid",
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 8,
    marginBottom: 10,
    lineHeight: 1.4,
  },
  watermark: {
    position: "absolute",
    left: 0,
    top: 0,
    right: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
    opacity: 0.06,
  },
  watermarkLogo: {
    width: 360,
    height: 360,
  },
  transcriptRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 8,
  },
  transcriptRole: {
    width: 68,
    fontSize: 10,
    fontWeight: 700,
    color: "#334155",
  },
  transcriptContent: {
    flex: 1,
    fontSize: 11,
    lineHeight: 1.45,
    whiteSpace: "pre-wrap",
  },
  referenceItem: {
    marginBottom: 6,
  },
  referencesTable: {
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderStyle: "solid",
    borderRadius: 8,
    overflow: "hidden",
  },
  referenceRow: {
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#f1f5f9",
    borderBottomStyle: "solid",
  },
  referenceRowLast: {
    borderBottomWidth: 0,
  },
  referenceRowTop: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
  },
  sourceBadge: {
    fontSize: 9,
    color: "#0b1220",
    backgroundColor: "#e2e8f0",
    paddingVertical: 2,
    paddingHorizontal: 6,
    borderRadius: 999,
  },
  referenceTitle: {
    flex: 1,
    fontSize: 10,
    fontWeight: 700,
    color: "#0b1220",
  },
  referenceLabel: {
    fontSize: 10,
    color: "#0b1220",
  },
  referenceMeta: {
    fontSize: 9,
    color: "#64748b",
    marginTop: 2,
  },
  footer: {
    position: "absolute",
    bottom: 18,
    left: 40,
    right: 40,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    borderTopStyle: "solid",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  footerText: {
    fontSize: 9,
    color: "#64748b",
  },
});
